### ISSUE TITLE
Scoreboard's: Wierd/Glitch

### ISSUE THREAD

**Issue by clovisd** [BattlePlugins/Tickets#4]
So, this is a screenshot I took on my server the other day while using a BattleGrounds arena.

![Screenshot]
( http://puu.sh/c8A42/ff65edb8a2.png)

In this specific case, it's a 2v2v2v2 (total of 8 players) arena. However, the leaderboard on the right side displays 9 name fields; at one point it had 10.

Zach's confirmed the issue with me on IRC. My understanding is we're planning a major overhaul of the side scoreboards.

**Comment by lDucks** [comment]
I'm assuming that this has been handled as it was opened a year ago.
