### ISSUE TITLE
Null pointer exception on any Join command

### ISSUE THREAD

**Issue by dether001** [BattlePlugins/Tickets#7]
Whenever I try to join an arena the server does nothing at all, in-game it gives me no error message or anything, just act like nothing happened, here's the error the console gives me: http://pastebin.com/xAd4fmQm

**Comment by Zach443** [comment]
That is an interesting error, I've never seen scoreboards do that type of thing.. Have you done any configuration other than set up your arena? If so, please paste your config

**Comment by Europia79** [comment]
The error says that there no MatchParams... which means that you missing one of the files. Simply rename or delete the /plugins/BattleArena folder... in order to regenerate it on the next server startup. You should then get all the necessary files... including the default MatchParams.

**Comment by Zach443** [comment]
Oooh, derp. I was looking at the wrong paste, lol. Yeah, Euro is right >.>

**Comment by dether001** [comment]
Thanks for the fast replys guys, I'll looking forward to do this as soon as I get home, I'll let you know about any news.
